@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

WeddingPlanner *-right-> "1" UniqueTagList
UniqueTagList -right-> "*" Tag
UniqueTagList -[hidden]down-> Wedding
WeddingPlanner *-right-> "1" UniqueWeddingList

UniqueWeddingList -right-> Wedding
Wedding -down-> Date
Wedding -down-> Title
Wedding --> Person : bride
Wedding --> Person : groom
Wedding -right-> UniquePersonList
UniquePersonList -->  Person: members

Person -right-> "*" Tag

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
@enduml
