@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WeddingPlannerParser" as WeddingPlannerParser LOGIC_COLOR
participant ":DeleteWeddingCommandParser" as DeleteWeddingCommandParser LOGIC_COLOR
participant "d:DeleteWeddingCommand" as DeleteWeddingCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box WeddingModel MODEL_COLOR_T1
participant "m:WeddingModel" as WeddingModel MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> WeddingPlannerParser : parseCommand("delete 1")
activate WeddingPlannerParser

create DeleteWeddingCommandParser
WeddingPlannerParser -> DeleteWeddingCommandParser
activate DeleteWeddingCommandParser

DeleteWeddingCommandParser --> WeddingPlannerParser
deactivate DeleteWeddingCommandParser

WeddingPlannerParser -> DeleteWeddingCommandParser : parse
activate DeleteWeddingCommandParser

create DeleteWeddingCommand
DeleteWeddingCommandParser -> DeleteWeddingCommand
activate DeleteWeddingCommand

DeleteWeddingCommand --> DeleteWeddingCommandParser :
deactivate DeleteWeddingCommand

DeleteWeddingCommandParser --> WeddingPlannerParser : d
deactivate DeleteWeddingCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteWeddingCommandParser -[hidden]-> WeddingPlannerParser
destroy DeleteWeddingCommandParser

WeddingPlannerParser --> LogicManager : d
deactivate WeddingPlannerParser

LogicManager -> DeleteWeddingCommand : execute
activate DeleteWeddingCommand

DeleteWeddingCommand -> WeddingModel : deleteWedding(1)
activate WeddingModel

WeddingModel --> DeleteWeddingCommand
deactivate WeddingModel

create CommandResult
DeleteWeddingCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteWeddingCommand
deactivate CommandResult

DeleteWeddingCommand --> LogicManager : r
deactivate DeleteWeddingCommand

[<--LogicManager
deactivate LogicManager
@enduml
