@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "WeddingPlanner Storage" #F4F6F6{
Class "<<interface>>\nWeddingPlannerStorage" as WeddingPlannerStorage
Class JsonWeddingPlannerStorage
Class JsonSerializableWeddingPlanner
Class JsonAdaptedWedding
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" WeddingPlannerStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> WeddingPlannerStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonWeddingPlannerStorage .up.|> WeddingPlannerStorage
JsonWeddingPlannerStorage ..> JsonSerializableWeddingPlanner
JsonSerializableWeddingPlanner --> "*" JsonAdaptedWedding
JsonAdaptedWedding --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
